import type { Metadata } from "next"
import { Chango } from "next/font/google"
import { Albert_Sans } from "next/font/google"
import "./globals.css"

export const metadata: Metadata = { title: "Create Next App", description: "Generated by create next app" }
export const chango = Chango({ subsets: ["latin"], weight: "400" })
export const albertSans = Albert_Sans({ subsets: ["latin"], weight: ["100", "400", "500", "700"] })

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="antialiased">{children}</body>
    </html>
  )
}
